
Item = int

class PriorityQueue:
    def push(self, score: int, item: Item) -> None: ...
    def pop(self) -> tuple[int, Item]: ...
    def change_score(self, item: Item, new_score: int) -> None: ...
    def get_score_by_item(self, item: Item) -> tuple | int | None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
